version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing Nodejs
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install -g yarn
      - cd commonwealth-front-end-task && yarn install

  build:
    commands:
      - echo Testing...
      - yarn test
      - yarn build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: commonwealth-front-end-task/build
